# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(395, 223)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 180, 251, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        self.label.setText("")
        self.label.setObjectName("label")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(270, 180, 121, 23))
        self.btn.setObjectName("btn")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label1 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label1)
        self.label3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label3.setObjectName("label3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label3)
        self.label4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label4.setObjectName("label4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label4)
        self.label5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label5.setObjectName("label5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label5)
        self.label2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label2.setObjectName("label2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.label6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label6.setObjectName("label6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label6)
        self.edit1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edit1.setObjectName("edit1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit1)
        self.edit2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edit2.setObjectName("edit2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit2)
        self.edit3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edit3.setObjectName("edit3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit3)
        self.edit4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edit4.setObjectName("edit4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit4)
        self.edit5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edit5.setObjectName("edit5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.edit5)
        self.edit6 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edit6.setObjectName("edit6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.edit6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EditForm"))
        self.btn.setText(_translate("MainWindow", "изменить"))
        self.label1.setText(_translate("MainWindow", "название сорта"))
        self.label3.setText(_translate("MainWindow", "степень обжарки"))
        self.label4.setText(_translate("MainWindow", "молотый/в зернах"))
        self.label5.setText(_translate("MainWindow", "вкус"))
        self.label2.setText(_translate("MainWindow", "цена упаковки"))
        self.label6.setText(_translate("MainWindow", "объем упаковки"))
